### ISSUE TITLE
Fallback URL?

### ISSUE THREAD

**Issue by tarasivashchuk** [MartiONE/scrapy-proxy-spiders#1]
Umm... yeah, what's up with fallback URL in this function?

https://github.com/MartiONE/scrapy-proxy-spiders/blob/f707a7a7d7237b54e1f422bfa28f88a0a1002914/ProxyFetcher/items.py#L29

**Comment by MartiONE** [comment]
I believe that at the time I wrote this, the fallback url was a free online judge. Which weirdly enough looks like it was using a porn site to doing that.

At least it make me laugh a little bit when you mentioned it haha.

Feel free to PR a more suitable candidate, I am not actively using or working on this.

**Comment by MartiONE** [comment]
Solved on the last commit: https://github.com/MartiONE/scrapy-proxy-spiders/commit/8218e0e119914811eb130372718ee7b6745b76d8
